services:
  - type: web
    name: carbazzar-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false # You will enter this securely in Render dashboard
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
